#!/bin/bash
# tests/04-ml/test-drift-baseline.sh
# Verifies that data/drift/baseline.json exists and contains valid
# training-set prediction baseline statistics.
#
# This file is generated by `ansible-playbook playbooks/12-evidently.yml`
# (Phase 1). It will later be mounted as a Kubernetes ConfigMap and read
# by the Evidently CronJob.
#
# Test assertions:
#   1. File exists at expected path
#   2. JSON is syntactically valid
#   3. Schema is correct (top-level keys, prediction_stats, histogram)
#   4. Statistics are within sane ranges for C-MAPSS RUL
#   5. Histogram counts sum equals training_set_size
#   6. Production model version matches the @production alias in MLflow

set -uo pipefail
source "$(dirname "$0")/../_lib.sh"

test_header "Drift detection baseline (training-set prediction distribution)"

BASELINE="/root/thesis-infra/data/drift/baseline.json"

# Test 1: File exists
if [ ! -f "$BASELINE" ]; then
  skip "Baseline file not found at $BASELINE" \
       "run ansible-playbook playbooks/12-evidently.yml first"
  exit 0
fi
pass "Baseline file exists ($BASELINE)"

# Test 2: Valid JSON
if ! python3 -c "import json; json.load(open('$BASELINE'))" 2>/dev/null; then
  fail "Baseline file is not valid JSON"
  exit 1
fi
pass "Baseline is valid JSON"

# Test 3: Schema is correct (required top-level fields)
SCHEMA_CHECK=$(python3 -c "
import json, sys
b = json.load(open('$BASELINE'))
required = ['generated_at', 'model_version', 'model_uri', 'training_set_size',
            'prediction_stats', 'histogram']
missing = [k for k in required if k not in b]
if missing:
    print(f'MISSING:{missing}')
else:
    print('OK')
" 2>/dev/null)

if [ "$SCHEMA_CHECK" = "OK" ]; then
  pass "Schema includes all required top-level fields"
else
  fail "Schema check failed" "$SCHEMA_CHECK"
fi

# Test 4: prediction_stats fields
STATS_CHECK=$(python3 -c "
import json
b = json.load(open('$BASELINE'))
s = b.get('prediction_stats', {})
required = ['mean', 'std', 'min', 'max', 'median', 'q25', 'q75']
missing = [k for k in required if k not in s]
if missing:
    print(f'MISSING:{missing}')
else:
    print('OK')
" 2>/dev/null)

if [ "$STATS_CHECK" = "OK" ]; then
  pass "prediction_stats has all required fields"
else
  fail "prediction_stats incomplete" "$STATS_CHECK"
fi

# Test 5: Statistics in sane ranges
SANITY=$(python3 -c "
import json
b = json.load(open('$BASELINE'))
s = b['prediction_stats']
errs = []
if not (0 <= s['mean'] <= 200): errs.append(f\"mean={s['mean']:.2f} out of [0,200]\")
if not (0 <= s['median'] <= 200): errs.append(f\"median={s['median']:.2f} out of [0,200]\")
if not (s['std'] > 0): errs.append(f\"std={s['std']:.2f} not positive\")
if not (s['min'] >= 0): errs.append(f\"min={s['min']:.2f} negative\")
if not (s['q25'] < s['median'] < s['q75']): errs.append('quantile order wrong')
print('OK' if not errs else ';'.join(errs))
" 2>/dev/null)

if [ "$SANITY" = "OK" ]; then
  pass "Statistics in sane ranges (mean, median in [0,200], q25<median<q75)"
else
  fail "Statistics out of sane range" "$SANITY"
fi

# Test 6: Histogram counts sum to training_set_size
HIST_SUM=$(python3 -c "
import json
b = json.load(open('$BASELINE'))
total = b['training_set_size']
counts_sum = sum(b['histogram']['counts'])
diff = abs(total - counts_sum)
if diff > total * 0.01:
    print(f\"MISMATCH:total={total},sum={counts_sum},diff={diff}\")
else:
    print(f\"OK:{counts_sum}/{total}\")
" 2>/dev/null)

if echo "$HIST_SUM" | grep -q "^OK:"; then
  detail=$(echo "$HIST_SUM" | sed 's/^OK://')
  pass "Histogram counts sum matches training_set_size ($detail)"
else
  fail "Histogram sum mismatch" "$HIST_SUM"
fi

# Test 7: Production model version matches MLflow @production alias
if kubectl get svc mlflow -n mlops >/dev/null 2>&1; then
  MLFLOW_VER=$(kubectl run drift-test-$$ --rm -i --restart=Never \
    --image=curlimages/curl:8.10.1 --quiet -- \
    curl -sf "http://mlflow.mlops.svc.cluster.local:5000/api/2.0/mlflow/registered-models/alias?name=cmapss-rul&alias=production" \
    2>/dev/null | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('model_version', {}).get('version', 'unknown'))
except Exception:
    print('error')
" 2>/dev/null)

  BASELINE_VER=$(python3 -c "import json; print(json.load(open('$BASELINE'))['model_version'])" 2>/dev/null)

  if [ -n "$MLFLOW_VER" ] && [ -n "$BASELINE_VER" ] && [ "$MLFLOW_VER" = "$BASELINE_VER" ]; then
    pass "Baseline model version matches MLflow @production alias (version $BASELINE_VER)"
  elif [ "$MLFLOW_VER" = "unknown" ] || [ "$MLFLOW_VER" = "error" ]; then
    info "Could not query MLflow @production alias (baseline=$BASELINE_VER)"
  else
    info "Baseline version ($BASELINE_VER) differs from current @production ($MLFLOW_VER)"
    info "  To refresh baseline: ansible-playbook playbooks/12-evidently.yml"
  fi
else
  skip "MLflow service not deployed — cannot verify version match"
fi

# Test 8: Summary stats printed for reference
info "Baseline summary:"
python3 -c "
import json
b = json.load(open('$BASELINE'))
s = b['prediction_stats']
print(f\"          Model:    {b['model_uri']} (v{b['model_version']})\")
print(f\"          Training: {b['training_set_size']} samples\")
print(f\"          Mean:     {s['mean']:.2f} cycles\")
print(f\"          Median:   {s['median']:.2f}\")
print(f\"          Std:      {s['std']:.2f}\")
print(f\"          IQR:      [{s['q25']:.2f}, {s['q75']:.2f}]\")
" 2>/dev/null | sed 's/^/    /'
